# Generated by Django 4.1.2 on 2023-03-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Genre2",
        ),
        migrations.DeleteModel(
            name="Genre3",
        ),
    ]
