# Generated by Django 3.2.6 on 2023-04-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tier'),
        ),
    ]
