# Generated by Django 4.1.2 on 2023-03-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_theme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="theme",
            old_name="theme_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="theme_name",
            new_name="name",
        ),
    ]
